import sys
import go

# file = open("/Users/mikebrgs/CurrentWork/tecnico/iasd/proj1/data/data8.txt", "r")
# game = go.Game()
# state = game.load_board(file)
# print(state)
# print(game.terminal_test(state))
# print(game.utility(state,1))
# print(game.utility(state,2))
# state = game.result(state,(2,5,4))
# print(state)
# print(game.terminal_test(state))
# print(game.utility(state,1))
# print(game.utility(state,2))

# file = open("/Users/mikebrgs/CurrentWork/tecnico/iasd/proj1/data/data9.txt", "r")
# game = go.Game()
# state = game.load_board(file)
# print(state)
# print(game.actions(state))

# file = open("/Users/mikebrgs/CurrentWork/tecnico/iasd/proj1/data/clean.txt", "r")
# state = go.State(6,1)
# print(state)
# print(state.getclusters())
# state.play(1,2,2)
# print(state)
# print(state.getclusters())
# state.play(2,4,2)
# print(state)
# print(state.getclusters())
# state.play(1,3,2)
# print(state)
# print(state.getclusters())
# state.play(2,4,3)
# print(state)
# print(state.getclusters())

# state.play(1,5,5)
# print(state)
# print(state.getclusters())
# state.play(2,4,4)
# print(state)
# print(state.getclusters())
# state.play(1,2,2)
# print(state)
# print(state.getclusters())
# state.play(1,2,2)
# print(state)
# print(state.getclusters())
# state.play(1,2,2)
# print(state)
# print(state.getclusters())
# state.play(1,2,2)
# print(state)
# print(state.getclusters())

file = open("/Users/mikebrgs/CurrentWork/tecnico/iasd/proj1/data/data10.txt", "r")
game = go.Game()
state = game.load_board(file)
print(state)
print(game.terminal_test(state))
state = game.result(state, (1,2,5))
print(state)
print(game.terminal_test(state))
print("***")
file = open("/Users/mikebrgs/CurrentWork/tecnico/iasd/proj1/data/data11.txt", "r")
game = go.Game()
state = game.load_board(file)
print(state)
print(game.terminal_test(state))
state = game.result(state, (2,2,5))
print(state)
print(game.terminal_test(state))
